#env specific infrastructure
apiVersion: v1
kind: Resource
metadata:
  name: postgres-1

spec:
  template:
    - name: test1
      infrastructure: postgres-db1/test
      element:
        database: tst_user

    - name: sit
      infrastructure: postgres-db1/test
      element:
        database: sit_user

    - name: alpha
      infrastructure: postgres-db1/alpha
      element:
        database: user

    - name: prod
      infrastructure: postgres-db1/prod
      element:
        database: user
